### ISSUE TITLE
Slime block false positive

### ISSUE THREAD

**Issue by Pantera07** [MWHunter/Grim#503] opened 2022-05-22 04:37 UTC
**Describe the bug**
Slime block false positive

**To Reproduce**
1.18.2 Vanilla
https://youtu.be/5_gHdP7hloM

**Server Version:**
GrimAC Official Server (2022-05-20)

**Grim Version (Git commit or the version in the jar's name)**
GrimAC Official Server (2022-05-20)

**Relevant plugins**
GrimAC Official Server (2022-05-20)

**Comment by MWHunter** [comment] 2022-05-28 22:32
Duplicate of https://github.com/MWHunter/Grim/issues/511 although this issue was first

**Closed by MWHunter** 2022-05-28 22:32 UTC
Labels: bug
