### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lordhadow1** [MWHunter/Grim#362] opened 2022-04-05 23:38 UTC
**Describe the bug**
2 Errors

**To Reproduce**
https://paste.twerion.net/oxecuvufiq.lua
https://paste.twerion.net/tesofujaqe.swift

**Server Version:**
![image](https://user-images.githubusercontent.com/73142735/161868283-d1b3d013-a595-4c05-a4d9-43fce074c905.png)

**Grim Version (Git commit or the version in the jar's name)**

Latets Grim Version

**Comment by MWHunter** [comment] 2022-04-06 03:33
caused by https://github.com/retrooper/packetevents/issues/307

**Comment by Elierrr** [comment] 2022-04-07 18:58
Issue tracked in CobbleSword/NachoSpigot#356

**Comment by MWHunter** [comment] 2022-04-11 02:23
Retrooper added a paper specific injector so this should be fixed whenever grim recompiles with latest packetevents.

**Closed by MWHunter** 2022-04-11 02:23 UTC
Labels: bug
