### ISSUE TITLE
PacketEvents Event is null

### ISSUE THREAD

**Issue by Pantera07** [MWHunter/Grim#369] opened 2022-04-08 13:44 UTC
**Describe the bug**
i got error message
https://pastebin.com/UYTXzNQW

**Server Version:**
Purpur 1.18.2 #1609

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.2.1-all

**Relevant plugins**
ProtocolLib 5.0.0-SNAPSHOT #553
Vulcan 2.6.4

**Comment by MWHunter** [comment] 2022-04-11 02:51
Caused by https://github.com/retrooper/packetevents/issues/240

**Comment by MWHunter** [comment] 2022-04-20 02:48
Will be fixed in next release as a packetevents commit has fixed this.

**Closed by MWHunter** 2022-04-20 02:48 UTC
Labels: bug
