### ISSUE TITLE
Sprinting backwards is not checked

### ISSUE THREAD

**Issue by derech1e** [MWHunter/Grim#139] opened 2021-04-21 16:41 UTC
If you sprint or sprint + jump backwards, it will not be recognized.

**Comment by MWHunter** [comment] 2021-04-21 16:42
Duplicate of https://github.com/MWHunter/Grim/issues/135

**Closed by MWHunter** 2021-04-21 16:42 UTC

**Comment by derech1e** [comment] 2021-04-21 16:51
Ah, ok
Sry
