### ISSUE TITLE
cancelled honey block break while jumping into it

### ISSUE THREAD

**Issue by ZugPilot** [MWHunter/Grim#445] opened 2022-04-29 17:19 UTC
**Describe the bug**

It is a false positive.

**To Reproduce**
Video is preferred.   If video is not possible, for bypasses, the hacked client name, version, module, module settings, and the check being bypassed is enough.  For false positives, steps to reproduce is fine also.

https://www.youtube.com/watch?v=7ufQ1TSldVg

**Server Version:**

1.18.2

**Grim Version (Git commit or the version in the jar's name)**

2.2.8

**Relevant plugins**
Or all plugins if you are unsure
tested on test.grim.ac

**Comment by MWHunter** [comment] 2022-05-05 02:33
Assuming caused by https://github.com/MWHunter/Grim/issues/458

**Comment by MWHunter** [comment] 2022-06-25 20:10
Fixed by https://github.com/MWHunter/Grim/commit/ceb144598fea9ff7b7703b61127de41a20066fe3

**Closed by MWHunter** 2022-06-25 20:10 UTC
Labels: bug
