### ISSUE TITLE
Running into connected cobblestone walls causing simulation false positives (1.8)

### ISSUE THREAD

**Issue by iFlamingoz** [MWHunter/Grim#469] opened 2022-05-07 10:26 UTC
**Describe the bug**
Running into connected cobblestone walls can sometimes cause simulation false positives.
The client used was also 1.8.8.

**To Reproduce**
https://youtu.be/GjoEW6R_FGc

**Server Version:** 1.8.8 NachoSpigot

**Grim Version (Git commit or the version in the jar's name)** 101909ed83cae6fe948c102182a71709b39113cd

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment] 2022-05-07 20:11
I can't fix this.  This is 1.8 clients having buggy collisions.

If you look, the client went from 0.083 -> -0.0784 in a single tick.  This is because the client saw vertical collision and set their y velocity to 0.  However, there is no vertical collision at all.

**Comment by MWHunter** [comment] 2022-05-07 20:21
Nevermind, able to reproduce on 1.9.  Have no clue what the game is thinking.

**Comment by MWHunter** [comment] 2022-05-07 20:34
oh, it's just 0.03.

**Comment by MWHunter** [comment] 2022-05-07 20:42
Fixed by https://github.com/MWHunter/Grim/commit/352049856a4f710cfb942abe5d974a94fadfba6c

**Closed by MWHunter** 2022-05-07 20:42 UTC
Labels: bug
