### ISSUE TITLE
[False] Grim STILL false-flags on sneak-jumping (C1.14.4 -> S1.18.2)

### ISSUE THREAD

**Issue by VidTu** [MWHunter/Grim#502] opened 2022-05-21 11:40 UTC
#451 is not fixed with the latest Grim version.

https://www.youtube.com/watch?v=MomHtlmf1mY

**Comment by MWHunter** [comment] 2022-05-28 23:37
Can you reproduce on a vanilla client?  I know of a cheat client that flags this without modules because they messed up some code.

**Comment by VidTu** [comment] 2022-05-29 00:44
It's a vanilla client, just a PolyMC launcher.

**Comment by VidTu** [comment] 2022-05-29 01:00
Just reproduced with the vanilla launcher. https://www.youtube.com/watch?v=wg07FQmC914

**Comment by MWHunter** [comment] 2022-05-29 02:12
Fixed by https://github.com/MWHunter/Grim/commit/54043c61b09a10390376493c025685beea225f58

**Closed by MWHunter** 2022-05-29 02:12 UTC
Labels: bug
