### ISSUE TITLE
False positives when placing blocks

### ISSUE THREAD

**Issue by hinoobers** [MWHunter/Grim#456] opened 2022-05-03 18:50 UTC
**Describe the bug**
False positive when while falling, attempting to negate your fall damage by placing blocks under you quickly
once you're close to the ground.

**To Reproduce**
Just use normal client, (i used vanilla), bridge up, start falling down and then while you're close to the ground
while falling, try to quickly place blocks under you.

**Server Version:**
Test Server

**Grim Version (Git commit or the version in the jar's name)**
Test Server

**Relevant plugins**
Test Server

**Comment by MWHunter** [comment] 2022-05-04 00:14
Unable to reproduce.  Can you upload a video?

**Comment by MWHunter** [comment] 2022-05-04 05:28
Assuming fixed by https://github.com/MWHunter/Grim/commit/e9457bdc5a7c060fee63a02b5e59e337e8acd0b4

**Closed by MWHunter** 2022-05-04 05:28 UTC
Labels: bug, invalid
